x = "Hello World!"
print (len(x))
print (x.index("o"))
print (x.index("H"))
print (x.count("l"))
print (x[3:7])
print (x[3:8:2])
print (x[::-1])
print (x[1].upper())
print (x[0] + x[1].upper() + x[2:])
print (x[2:7])
print (x[-3])
print (x[-2: ])
print (x[2: ])
print (x[ :-2])
print (x.upper())
print (x.lower())
print (x.startswith("He"))
print (x.endswith("abc"))
print (x.split(" "))
print (x.split("l"))
print (x.split("o"))
